INFO 2024-03-23 23:58:03,989 autoreload 12300 15724 Watching for file changes with StatReloader
INFO 2024-03-23 23:58:06,527 basehttp 12300 14772 "GET / HTTP/1.1" 200 13
INFO 2024-03-23 23:58:13,279 basehttp 12300 14772 "GET / HTTP/1.1" 200 13
INFO 2024-03-23 23:58:20,989 basehttp 12300 14772 "GET /cub/ HTTP/1.1" 200 1
INFO 2024-03-27 22:13:01,056 autoreload 18028 16176 Watching for file changes with StatReloader
INFO 2024-03-27 22:13:02,660 basehttp 18028 12456 "GET / HTTP/1.1" 200 13
WARNING 2024-03-27 22:13:02,926 log 18028 12456 Not Found: /favicon.ico
WARNING 2024-03-27 22:13:02,927 basehttp 18028 12456 "GET /favicon.ico HTTP/1.1" 404 2951
INFO 2024-03-27 22:13:09,578 basehttp 18028 12456 "GET /about HTTP/1.1" 301 0
INFO 2024-03-27 22:13:09,582 basehttp 18028 10420 "GET /about/ HTTP/1.1" 200 8
INFO 2024-03-27 22:13:34,449 basehttp 18028 10420 "GET /about/ HTTP/1.1" 200 8
INFO 2024-03-27 22:13:42,049 basehttp 18028 10420 "GET /heads HTTP/1.1" 301 0
INFO 2024-03-27 22:13:42,051 basehttp 18028 16100 "GET /heads/ HTTP/1.1" 200 10
INFO 2024-03-27 22:13:45,369 basehttp 18028 16100 "GET /heads/ HTTP/1.1" 200 8
INFO 2024-03-27 22:13:48,939 basehttp 18028 16100 "GET /cub HTTP/1.1" 301 0
INFO 2024-03-27 22:13:48,941 basehttp 18028 5844 "GET /cub/ HTTP/1.1" 200 1
INFO 2024-03-27 22:13:54,263 basehttp 18028 5844 "GET /cub/ HTTP/1.1" 200 1
INFO 2024-03-27 22:13:58,300 basehttp 18028 5844 "GET /numbers HTTP/1.1" 301 0
INFO 2024-03-27 22:13:58,303 basehttp 18028 10040 "GET /numbers/ HTTP/1.1" 200 3
INFO 2024-03-27 22:26:32,944 autoreload 18028 16176 D:\GeekBrains\Django\Seminars\myproject\myapp\models.py changed, reloading.
INFO 2024-03-27 22:35:42,215 autoreload 15136 5000 Watching for file changes with StatReloader
INFO 2024-03-27 22:36:11,865 autoreload 15136 5000 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 22:36:12,265 autoreload 16012 13780 Watching for file changes with StatReloader
INFO 2024-03-27 22:36:15,785 autoreload 11788 4672 Watching for file changes with StatReloader
INFO 2024-03-27 22:36:19,314 basehttp 11788 3908 "GET / HTTP/1.1" 200 13
ERROR 2024-03-27 22:36:25,003 log 11788 3908 Internal Server Error: /heads/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Решка'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp\views.py", line 17, in heads_or_tails
    choice_coin.save()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 1036, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 1080, in _do_update
    filtered = base_qs.filter(pk=pk_val)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\lookups.py", line 364, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'Решка'.
ERROR 2024-03-27 22:36:25,008 basehttp 11788 3908 "GET /heads/ HTTP/1.1" 500 143400
INFO 2024-03-27 22:37:27,225 autoreload 11788 4672 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 22:37:30,566 autoreload 16264 5760 Watching for file changes with StatReloader
INFO 2024-03-27 22:37:32,108 basehttp 16264 15764 "GET / HTTP/1.1" 200 13
INFO 2024-03-27 22:37:37,167 basehttp 16264 15764 "GET /heads/ HTTP/1.1" 200 116
INFO 2024-03-27 22:38:22,628 autoreload 16264 5760 D:\GeekBrains\Django\Seminars\myproject\myapp\migrations\0001_initial.py changed, reloading.
INFO 2024-03-27 22:38:24,948 autoreload 14292 11884 Watching for file changes with StatReloader
INFO 2024-03-27 22:38:26,193 basehttp 14292 17912 "GET / HTTP/1.1" 200 13
INFO 2024-03-27 22:38:32,167 basehttp 14292 17912 "GET /heads/ HTTP/1.1" 200 116
INFO 2024-03-27 22:57:45,973 autoreload 14292 11884 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 22:57:46,395 autoreload 328 17404 Watching for file changes with StatReloader
INFO 2024-03-27 23:01:35,934 autoreload 328 17404 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 23:01:36,379 autoreload 18088 15968 Watching for file changes with StatReloader
INFO 2024-03-27 23:01:44,717 autoreload 14292 12104 Watching for file changes with StatReloader
INFO 2024-03-27 23:01:45,857 basehttp 14292 8528 "GET / HTTP/1.1" 200 13
INFO 2024-03-27 23:01:55,989 basehttp 14292 8528 "GET /coin_values HTTP/1.1" 301 0
INFO 2024-03-27 23:01:55,995 basehttp 14292 11612 "GET /coin_values/ HTTP/1.1" 200 5
INFO 2024-03-27 23:08:03,400 autoreload 14292 12104 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 23:08:03,810 autoreload 16476 1880 Watching for file changes with StatReloader
INFO 2024-03-27 23:08:06,531 autoreload 14636 10116 Watching for file changes with StatReloader
INFO 2024-03-27 23:08:07,685 basehttp 14636 15564 "GET / HTTP/1.1" 200 13
ERROR 2024-03-27 23:08:14,155 log 14636 15564 Internal Server Error: /coin_values/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp\views.py", line 22, in coin_values
    return HttpResponse(val for val in value)
                       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
ERROR 2024-03-27 23:08:14,157 basehttp 14636 15564 "GET /coin_values/ HTTP/1.1" 500 65111
INFO 2024-03-27 23:10:30,119 autoreload 14636 10116 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 23:10:30,530 autoreload 10328 11932 Watching for file changes with StatReloader
INFO 2024-03-27 23:10:33,240 autoreload 11800 15576 Watching for file changes with StatReloader
INFO 2024-03-27 23:10:34,461 basehttp 11800 11032 "GET / HTTP/1.1" 200 13
ERROR 2024-03-27 23:10:39,126 log 11800 11032 Internal Server Error: /coin_values/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp\views.py", line 23, in coin_values
    for text in value:
TypeError: 'NoneType' object is not iterable
ERROR 2024-03-27 23:10:39,126 basehttp 11800 11032 "GET /coin_values/ HTTP/1.1" 500 65208
INFO 2024-03-27 23:11:16,283 autoreload 11800 15576 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 23:11:16,700 autoreload 224 16032 Watching for file changes with StatReloader
INFO 2024-03-27 23:11:19,690 autoreload 15020 7960 Watching for file changes with StatReloader
INFO 2024-03-27 23:11:22,931 basehttp 15020 17696 "GET / HTTP/1.1" 200 13
ERROR 2024-03-27 23:11:26,430 log 15020 17696 Internal Server Error: /coin_values/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp\views.py", line 23, in coin_values
    for text in value:
TypeError: 'NoneType' object is not iterable
ERROR 2024-03-27 23:11:26,430 basehttp 15020 17696 "GET /coin_values/ HTTP/1.1" 500 65224
INFO 2024-03-27 23:13:11,767 autoreload 15020 7960 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 23:13:12,262 autoreload 17956 4980 Watching for file changes with StatReloader
INFO 2024-03-27 23:13:13,603 basehttp 17956 17620 "GET / HTTP/1.1" 200 13
INFO 2024-03-27 23:13:16,690 basehttp 17956 17620 "GET /coin_values/ HTTP/1.1" 200 6
INFO 2024-03-27 23:13:17,508 basehttp 17956 17620 "GET /coin_values/ HTTP/1.1" 200 6
INFO 2024-03-27 23:13:41,016 autoreload 17956 4980 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 23:13:41,445 autoreload 16672 18024 Watching for file changes with StatReloader
INFO 2024-03-27 23:13:42,610 basehttp 16672 15296 "GET / HTTP/1.1" 200 13
INFO 2024-03-27 23:13:45,020 basehttp 16672 15296 "GET /coin_values/ HTTP/1.1" 200 6
INFO 2024-03-27 23:13:45,581 basehttp 16672 15296 "GET /coin_values/ HTTP/1.1" 200 6
INFO 2024-03-27 23:14:24,425 autoreload 16672 18024 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 23:14:24,840 autoreload 16324 10004 Watching for file changes with StatReloader
INFO 2024-03-27 23:14:28,239 basehttp 16324 7580 "GET / HTTP/1.1" 200 13
ERROR 2024-03-27 23:14:30,789 log 16324 7580 Internal Server Error: /coin_values/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp\views.py", line 22, in coin_values
    print(type(list(value)))
               ^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
ERROR 2024-03-27 23:14:30,790 basehttp 16324 7580 "GET /coin_values/ HTTP/1.1" 500 65356
ERROR 2024-03-27 23:14:31,405 log 16324 7580 Internal Server Error: /coin_values/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp\views.py", line 22, in coin_values
    print(type(list(value)))
               ^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
ERROR 2024-03-27 23:14:31,407 basehttp 16324 7580 "GET /coin_values/ HTTP/1.1" 500 65082
INFO 2024-03-27 23:15:18,038 autoreload 16324 10004 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 23:15:18,455 autoreload 17640 17124 Watching for file changes with StatReloader
INFO 2024-03-27 23:15:34,955 basehttp 17640 13060 "GET / HTTP/1.1" 200 13
INFO 2024-03-27 23:15:37,683 basehttp 17640 13060 "GET /coin_values/ HTTP/1.1" 200 6
INFO 2024-03-27 23:15:38,390 basehttp 17640 13060 "GET /coin_values/ HTTP/1.1" 200 6
INFO 2024-03-27 23:16:27,825 autoreload 17640 17124 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 23:16:28,223 autoreload 14560 15652 Watching for file changes with StatReloader
INFO 2024-03-27 23:16:29,708 basehttp 14560 10512 "GET / HTTP/1.1" 200 13
INFO 2024-03-27 23:16:32,572 basehttp 14560 10512 "GET /coin_values/ HTTP/1.1" 200 234
INFO 2024-03-27 23:16:33,237 basehttp 14560 10512 "GET /coin_values/ HTTP/1.1" 200 234
INFO 2024-03-27 23:16:52,916 autoreload 14560 15652 D:\GeekBrains\Django\Seminars\myproject\myapp\views.py changed, reloading.
INFO 2024-03-27 23:16:53,310 autoreload 12948 17832 Watching for file changes with StatReloader
INFO 2024-03-27 23:16:54,602 basehttp 12948 18192 "GET / HTTP/1.1" 200 13
INFO 2024-03-27 23:16:58,667 basehttp 12948 18192 "GET /coin_values/ HTTP/1.1" 200 240
INFO 2024-03-27 23:16:59,288 basehttp 12948 18192 "GET /coin_values/ HTTP/1.1" 200 240
INFO 2024-03-27 23:19:38,098 autoreload 12948 17832 D:\GeekBrains\Django\Seminars\myproject\myapp\models.py changed, reloading.
INFO 2024-03-27 23:19:38,516 autoreload 16252 8324 Watching for file changes with StatReloader
INFO 2024-03-27 23:20:07,169 autoreload 16252 8324 D:\GeekBrains\Django\Seminars\myproject\myapp\models.py changed, reloading.
INFO 2024-03-27 23:20:07,635 autoreload 6332 4992 Watching for file changes with StatReloader
INFO 2024-03-27 23:21:48,339 autoreload 6332 4992 D:\GeekBrains\Django\Seminars\myproject\myapp\models.py changed, reloading.
INFO 2024-03-27 23:21:48,788 autoreload 5732 5716 Watching for file changes with StatReloader
INFO 2024-03-27 23:23:10,977 autoreload 5732 5716 D:\GeekBrains\Django\Seminars\myproject\myapp\models.py changed, reloading.
INFO 2024-03-27 23:23:11,438 autoreload 10800 9376 Watching for file changes with StatReloader
INFO 2024-03-27 23:29:02,747 autoreload 10800 9376 D:\GeekBrains\Django\Seminars\myproject\myapp\models.py changed, reloading.
INFO 2024-03-27 23:29:03,180 autoreload 18248 11584 Watching for file changes with StatReloader
INFO 2024-03-27 23:45:52,471 autoreload 18416 7884 Watching for file changes with StatReloader
WARNING 2024-03-27 23:45:53,856 log 18416 5740 Not Found: /
WARNING 2024-03-27 23:45:53,856 basehttp 18416 5740 "GET / HTTP/1.1" 404 2271
INFO 2024-03-27 23:46:13,815 basehttp 18416 5740 "GET /blog HTTP/1.1" 200 7
INFO 2024-03-27 23:58:14,564 autoreload 13180 11312 Watching for file changes with StatReloader
WARNING 2024-03-27 23:58:15,715 log 13180 17680 Not Found: /
WARNING 2024-03-27 23:58:15,715 basehttp 13180 17680 "GET / HTTP/1.1" 404 2271
WARNING 2024-03-27 23:58:23,647 log 13180 17680 Not Found: /blog/fake_data
WARNING 2024-03-27 23:58:23,647 basehttp 13180 17680 "GET /blog/fake_data HTTP/1.1" 404 2570
INFO 2024-03-27 23:58:55,418 autoreload 13180 11312 D:\GeekBrains\Django\Seminars\myproject\blogapp\urls.py changed, reloading.
INFO 2024-03-27 23:58:55,822 autoreload 17404 10212 Watching for file changes with StatReloader
WARNING 2024-03-27 23:58:57,385 log 17404 9056 Not Found: /
WARNING 2024-03-27 23:58:57,387 basehttp 17404 9056 "GET / HTTP/1.1" 404 2271
WARNING 2024-03-27 23:59:06,265 log 17404 9056 Not Found: /blog/fake_data
WARNING 2024-03-27 23:59:06,266 basehttp 17404 9056 "GET /blog/fake_data HTTP/1.1" 404 2571
INFO 2024-03-28 00:01:21,275 autoreload 17404 10212 D:\GeekBrains\Django\Seminars\myproject\blogapp\views.py changed, reloading.
INFO 2024-03-28 00:01:21,710 autoreload 11056 16156 Watching for file changes with StatReloader
WARNING 2024-03-28 00:03:56,175 log 11056 13852 Not Found: /
WARNING 2024-03-28 00:03:56,175 basehttp 11056 13852 "GET / HTTP/1.1" 404 2271
INFO 2024-03-28 00:03:56,508 autoreload 11056 16156 D:\GeekBrains\Django\Seminars\myproject\blogapp\models.py changed, reloading.
INFO 2024-03-28 00:03:57,020 autoreload 1796 17996 Watching for file changes with StatReloader
WARNING 2024-03-28 00:04:07,494 log 1796 18400 Not Found: /blog/fake_data
WARNING 2024-03-28 00:04:07,494 basehttp 1796 18400 "GET /blog/fake_data HTTP/1.1" 404 2571
INFO 2024-03-28 00:05:53,040 autoreload 1796 17996 D:\GeekBrains\Django\Seminars\myproject\blogapp\urls.py changed, reloading.
INFO 2024-03-28 00:05:53,477 autoreload 14628 6052 Watching for file changes with StatReloader
INFO 2024-03-28 00:06:28,487 autoreload 16588 13716 Watching for file changes with StatReloader
INFO 2024-03-28 00:06:44,917 autoreload 16588 13716 D:\GeekBrains\Django\Seminars\myproject\blogapp\urls.py changed, reloading.
INFO 2024-03-28 00:06:47,720 autoreload 12532 15452 Watching for file changes with StatReloader
WARNING 2024-03-28 00:06:50,000 log 12532 16856 Not Found: /
WARNING 2024-03-28 00:06:50,002 basehttp 12532 16856 "GET / HTTP/1.1" 404 2271
WARNING 2024-03-28 00:06:59,928 log 12532 16856 Not Found: /blog/add_author
WARNING 2024-03-28 00:06:59,930 basehttp 12532 16856 "GET /blog/add_author HTTP/1.1" 404 2575
INFO 2024-03-28 00:08:39,702 autoreload 12532 15452 D:\GeekBrains\Django\Seminars\myproject\blogapp\urls.py changed, reloading.
INFO 2024-03-28 00:08:40,139 autoreload 17620 11980 Watching for file changes with StatReloader
INFO 2024-03-28 00:09:55,643 autoreload 10832 17428 Watching for file changes with StatReloader
WARNING 2024-03-28 00:11:00,982 log 10832 14792 Not Found: /
WARNING 2024-03-28 00:11:00,983 basehttp 10832 14792 "GET / HTTP/1.1" 404 2271
INFO 2024-03-28 00:11:05,021 basehttp 10832 14792 "GET /blog HTTP/1.1" 200 7
WARNING 2024-03-28 00:11:10,485 log 10832 14792 Not Found: /about/
WARNING 2024-03-28 00:11:10,486 basehttp 10832 14792 "GET /about/ HTTP/1.1" 404 2307
WARNING 2024-03-28 00:11:14,684 log 10832 14792 Not Found: /add_author
WARNING 2024-03-28 00:11:14,684 basehttp 10832 14792 "GET /add_author HTTP/1.1" 404 2319
WARNING 2024-03-28 00:11:29,562 log 10832 14792 Not Found: /blog/add_author
WARNING 2024-03-28 00:11:29,563 basehttp 10832 14792 "GET /blog/add_author HTTP/1.1" 404 2576
INFO 2024-03-28 00:14:21,863 autoreload 10832 17428 D:\GeekBrains\Django\Seminars\myproject\myproject\urls.py changed, reloading.
INFO 2024-03-28 00:14:22,274 autoreload 16984 14460 Watching for file changes with StatReloader
INFO 2024-03-28 00:14:24,573 autoreload 11688 8900 Watching for file changes with StatReloader
WARNING 2024-03-28 00:14:25,535 log 11688 5860 Not Found: /
WARNING 2024-03-28 00:14:25,535 basehttp 11688 5860 "GET / HTTP/1.1" 404 2510
INFO 2024-03-28 00:14:32,864 basehttp 11688 5860 "GET /index HTTP/1.1" 200 7
WARNING 2024-03-28 00:14:37,775 log 11688 5860 Not Found: /about/
WARNING 2024-03-28 00:14:37,775 basehttp 11688 5860 "GET /about/ HTTP/1.1" 404 2546
INFO 2024-03-28 00:14:41,548 basehttp 11688 5860 "GET /add_author HTTP/1.1" 301 0
ERROR 2024-03-28 00:14:41,621 log 11688 6356 Internal Server Error: /add_author/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: blogapp_author.birthday

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\blogapp\views.py", line 13, in add_author
    author.save()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: blogapp_author.birthday
ERROR 2024-03-28 00:14:41,626 basehttp 11688 6356 "GET /add_author/ HTTP/1.1" 500 148146
INFO 2024-03-28 00:15:43,084 autoreload 11688 8900 D:\GeekBrains\Django\Seminars\myproject\blogapp\views.py changed, reloading.
INFO 2024-03-28 00:15:43,494 autoreload 9932 5776 Watching for file changes with StatReloader
INFO 2024-03-28 00:15:55,913 autoreload 9932 5776 D:\GeekBrains\Django\Seminars\myproject\blogapp\urls.py changed, reloading.
INFO 2024-03-28 00:15:56,327 autoreload 2864 2620 Watching for file changes with StatReloader
INFO 2024-03-28 00:15:57,382 basehttp 2864 3448 "GET / HTTP/1.1" 200 7
WARNING 2024-03-28 00:16:00,472 log 2864 3448 Not Found: /about/
WARNING 2024-03-28 00:16:00,472 basehttp 2864 3448 "GET /about/ HTTP/1.1" 404 2541
INFO 2024-03-28 00:16:04,661 basehttp 2864 3448 "GET /add_author/ HTTP/1.1" 200 49
INFO 2024-03-28 00:18:34,894 autoreload 2864 2620 D:\GeekBrains\Django\Seminars\myproject\blogapp\models.py changed, reloading.
INFO 2024-03-28 00:19:32,053 autoreload 17480 8712 Watching for file changes with StatReloader
INFO 2024-03-28 00:19:33,064 basehttp 17480 17396 "GET / HTTP/1.1" 200 7
WARNING 2024-03-28 00:19:36,042 log 17480 17396 Not Found: /about/
WARNING 2024-03-28 00:19:36,043 basehttp 17480 17396 "GET /about/ HTTP/1.1" 404 2541
INFO 2024-03-28 00:19:37,496 basehttp 17480 17396 "GET /add_author/ HTTP/1.1" 200 49
INFO 2024-04-01 13:23:23,563 autoreload 6660 4796 Watching for file changes with StatReloader
INFO 2024-04-01 13:23:39,028 autoreload 6660 4796 D:\GeekBrains\Django\Seminars\myproject\myapp3\urls.py changed, reloading.
INFO 2024-04-01 13:23:39,425 autoreload 15932 6616 Watching for file changes with StatReloader
WARNING 2024-04-01 13:23:42,979 log 15932 2524 Not Found: /
WARNING 2024-04-01 13:23:42,979 basehttp 15932 2524 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-01 13:23:48,386 log 15932 2524 Not Found: /myapp3
WARNING 2024-04-01 13:23:48,386 basehttp 15932 2524 "GET /myapp3 HTTP/1.1" 404 2420
WARNING 2024-04-01 13:23:51,418 log 15932 2524 Not Found: /myapp3/index
WARNING 2024-04-01 13:23:51,418 basehttp 15932 2524 "GET /myapp3/index HTTP/1.1" 404 2715
INFO 2024-04-01 13:24:10,161 basehttp 15932 2524 "GET /myapp3/index/index HTTP/1.1" 301 0
ERROR 2024-04-01 13:24:10,264 log 15932 9524 Internal Server Error: /myapp3/index/index/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py", line 6, in index
    return render('myapp3/index.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loaders\base.py", line 17, in get_template
    for origin in self.get_template_sources(template_name):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 70, in get_template_sources
    yield from loader.get_template_sources(template_name)
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loaders\filesystem.py", line 35, in get_template_sources
    name = safe_join(template_dir, template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
                         ^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 147, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
ERROR 2024-04-01 13:24:10,268 basehttp 15932 9524 "GET /myapp3/index/index/ HTTP/1.1" 500 119907
INFO 2024-04-01 13:25:02,303 autoreload 15932 6616 D:\GeekBrains\Django\Seminars\myproject\myapp3\urls.py changed, reloading.
INFO 2024-04-01 13:25:02,716 autoreload 5588 17336 Watching for file changes with StatReloader
WARNING 2024-04-01 13:25:03,963 log 5588 18144 Not Found: /
WARNING 2024-04-01 13:25:03,964 basehttp 5588 18144 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-01 13:25:11,875 log 5588 18144 Not Found: /index/
WARNING 2024-04-01 13:25:11,875 basehttp 5588 18144 "GET /index/ HTTP/1.1" 404 2420
WARNING 2024-04-01 13:25:12,911 log 5588 18144 Not Found: /index/
WARNING 2024-04-01 13:25:12,911 basehttp 5588 18144 "GET /index/ HTTP/1.1" 404 2420
WARNING 2024-04-01 13:25:24,657 log 5588 18144 Not Found: /myapp3
WARNING 2024-04-01 13:25:24,658 basehttp 5588 18144 "GET /myapp3 HTTP/1.1" 404 2420
INFO 2024-04-01 13:25:26,546 basehttp 5588 18144 "GET /myapp3/index HTTP/1.1" 301 0
ERROR 2024-04-01 13:25:26,577 log 5588 1768 Internal Server Error: /myapp3/index/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py", line 6, in index
    return render('myapp3/index.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loaders\base.py", line 17, in get_template
    for origin in self.get_template_sources(template_name):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 70, in get_template_sources
    yield from loader.get_template_sources(template_name)
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loaders\filesystem.py", line 35, in get_template_sources
    name = safe_join(template_dir, template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
                         ^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 147, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
ERROR 2024-04-01 13:25:26,580 basehttp 5588 1768 "GET /myapp3/index/ HTTP/1.1" 500 120108
INFO 2024-04-01 13:26:13,304 autoreload 5588 17336 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-01 13:26:13,716 autoreload 11744 4836 Watching for file changes with StatReloader
INFO 2024-04-01 13:26:14,735 basehttp 11744 1712 "GET /myapp3/index/ HTTP/1.1" 200 1266
INFO 2024-04-01 13:28:43,356 autoreload 11744 4836 D:\GeekBrains\Django\Seminars\myproject\myapp3\urls.py changed, reloading.
INFO 2024-04-01 13:28:43,773 autoreload 6692 4012 Watching for file changes with StatReloader
WARNING 2024-04-01 13:28:44,751 log 6692 16780 Not Found: /
WARNING 2024-04-01 13:28:44,751 basehttp 6692 16780 "GET / HTTP/1.1" 404 2384
INFO 2024-04-01 13:28:49,209 basehttp 6692 16780 "GET /myapp3 HTTP/1.1" 301 0
INFO 2024-04-01 13:28:49,214 basehttp 6692 4648 "GET /myapp3/ HTTP/1.1" 200 1075
INFO 2024-04-01 13:29:11,871 basehttp 6692 4648 "GET /myapp3/ HTTP/1.1" 200 1075
INFO 2024-04-01 13:29:12,562 autoreload 6692 4012 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-01 13:29:12,983 autoreload 3708 16740 Watching for file changes with StatReloader
INFO 2024-04-01 13:29:13,129 basehttp 3708 17252 "GET /myapp3/ HTTP/1.1" 200 859
INFO 2024-04-01 13:29:14,717 basehttp 3708 17252 "GET /myapp3/index/ HTTP/1.1" 200 1270
INFO 2024-04-01 13:29:16,665 basehttp 3708 17252 "GET /myapp3/about HTTP/1.1" 301 0
INFO 2024-04-01 13:29:16,668 basehttp 3708 15204 "GET /myapp3/about/ HTTP/1.1" 200 1074
INFO 2024-04-01 13:29:18,168 basehttp 3708 15204 "GET /myapp3/index/ HTTP/1.1" 200 1270
INFO 2024-04-01 13:29:39,707 basehttp 3708 15204 "GET /myapp3/ HTTP/1.1" 200 859
INFO 2024-04-01 13:29:40,663 autoreload 3708 16740 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-01 13:29:41,087 autoreload 11456 9296 Watching for file changes with StatReloader
INFO 2024-04-01 13:29:41,291 basehttp 11456 10864 "GET /myapp3/ HTTP/1.1" 200 859
INFO 2024-04-01 13:29:42,738 basehttp 11456 10864 "GET /myapp3/index/ HTTP/1.1" 200 1261
INFO 2024-04-01 13:29:46,345 basehttp 11456 10864 "GET /myapp3/about/ HTTP/1.1" 200 1074
INFO 2024-04-01 13:29:47,664 basehttp 11456 10864 "GET /myapp3/index/ HTTP/1.1" 200 1261
INFO 2024-04-01 13:29:49,255 basehttp 11456 10864 "GET /myapp3/about/ HTTP/1.1" 200 1074
WARNING 2024-04-01 13:40:17,996 log 11456 7004 Not Found: /
WARNING 2024-04-01 13:40:17,996 basehttp 11456 7004 "GET / HTTP/1.1" 404 2384
ERROR 2024-04-01 13:40:24,135 log 11456 7004 Internal Server Error: /myapp3/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py", line 16, in main
    return render(request, 'myapp3/main.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'end', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2024-04-01 13:40:24,139 basehttp 11456 7004 "GET /myapp3/ HTTP/1.1" 500 158859
INFO 2024-04-01 13:43:37,180 basehttp 11456 7004 "GET /myapp3/ HTTP/1.1" 200 865
INFO 2024-04-01 13:43:39,675 basehttp 11456 7004 "GET /myapp3/index/ HTTP/1.1" 200 1262
INFO 2024-04-01 13:43:41,797 basehttp 11456 7004 "GET /myapp3/about/ HTTP/1.1" 200 1071
INFO 2024-04-01 14:51:58,851 basehttp 11456 11900 "GET /myapp3/index/ HTTP/1.1" 200 1262
INFO 2024-04-01 14:52:01,842 basehttp 11456 11900 "GET /myapp3/about/ HTTP/1.1" 200 1071
INFO 2024-04-01 14:52:04,153 basehttp 11456 11900 "GET /myapp3/index/ HTTP/1.1" 200 1262
INFO 2024-04-01 15:01:03,159 autoreload 11456 9296 D:\GeekBrains\Django\Seminars\myproject\myapp3\models.py changed, reloading.
INFO 2024-04-01 15:01:03,583 autoreload 14900 4484 Watching for file changes with StatReloader
INFO 2024-04-01 15:07:07,209 autoreload 14900 4484 D:\GeekBrains\Django\Seminars\myproject\myapp3\models.py changed, reloading.
INFO 2024-04-01 15:07:07,699 autoreload 6188 2004 Watching for file changes with StatReloader
INFO 2024-04-01 15:45:09,600 autoreload 11576 7728 Watching for file changes with StatReloader
WARNING 2024-04-01 15:45:10,880 log 11576 1248 Not Found: /
WARNING 2024-04-01 15:45:10,881 basehttp 11576 1248 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-01 15:45:15,827 log 11576 1248 Not Found: /myapp3/
WARNING 2024-04-01 15:45:15,828 basehttp 11576 1248 "GET /myapp3/ HTTP/1.1" 404 3024
INFO 2024-04-01 15:45:25,937 basehttp 11576 1248 "GET /myapp3/cub/10 HTTP/1.1" 301 0
INFO 2024-04-01 15:45:25,946 basehttp 11576 10212 "GET /myapp3/cub/10/ HTTP/1.1" 200 1234
WARNING 2024-04-01 15:48:38,591 log 11576 10212 Not Found: /
WARNING 2024-04-01 15:48:38,591 basehttp 11576 10212 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-01 15:48:42,296 log 11576 10212 Not Found: /myapp3/
WARNING 2024-04-01 15:48:42,296 basehttp 11576 10212 "GET /myapp3/ HTTP/1.1" 404 3024
WARNING 2024-04-01 15:48:43,490 log 11576 10212 Not Found: /myapp3/
WARNING 2024-04-01 15:48:43,491 basehttp 11576 10212 "GET /myapp3/ HTTP/1.1" 404 3024
WARNING 2024-04-01 15:48:51,862 log 11576 10212 Not Found: /
WARNING 2024-04-01 15:48:51,862 basehttp 11576 10212 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-01 15:48:54,848 log 11576 10212 Not Found: /coin_values/
WARNING 2024-04-01 15:48:54,848 basehttp 11576 10212 "GET /coin_values/ HTTP/1.1" 404 2438
WARNING 2024-04-01 15:48:55,879 log 11576 10212 Not Found: /cub
WARNING 2024-04-01 15:48:55,879 basehttp 11576 10212 "GET /cub HTTP/1.1" 404 2411
WARNING 2024-04-01 15:48:57,895 log 11576 10212 Not Found: /cub/10
WARNING 2024-04-01 15:48:57,895 basehttp 11576 10212 "GET /cub/10 HTTP/1.1" 404 2420
WARNING 2024-04-01 15:49:08,787 log 11576 10212 Not Found: /myapp/cub/10
WARNING 2024-04-01 15:49:08,787 basehttp 11576 10212 "GET /myapp/cub/10 HTTP/1.1" 404 2438
INFO 2024-04-01 15:49:27,667 basehttp 11576 10212 "GET /myapp3/cub/10/ HTTP/1.1" 200 1322
INFO 2024-04-01 15:52:53,427 autoreload 11576 7728 D:\GeekBrains\Django\Seminars\myproject\myapp3\urls.py changed, reloading.
INFO 2024-04-01 15:52:53,958 autoreload 9096 7024 Watching for file changes with StatReloader
WARNING 2024-04-01 15:52:55,181 log 9096 3592 Not Found: /
WARNING 2024-04-01 15:52:55,182 basehttp 9096 3592 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-01 15:52:58,341 log 9096 3592 Not Found: /myapp3/
WARNING 2024-04-01 15:52:58,341 basehttp 9096 3592 "GET /myapp3/ HTTP/1.1" 404 3410
INFO 2024-04-01 15:53:01,865 basehttp 9096 3592 "GET /myapp3/cub/10/ HTTP/1.1" 200 892
INFO 2024-04-01 15:53:52,617 basehttp 9096 3592 "GET /myapp3/numbers/10 HTTP/1.1" 301 0
INFO 2024-04-01 15:53:52,620 basehttp 9096 18096 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1327
INFO 2024-04-01 15:54:01,008 basehttp 9096 18096 "GET /myapp3/coin/10 HTTP/1.1" 301 0
ERROR 2024-04-01 15:54:01,035 log 9096 10444 Internal Server Error: /myapp3/coin/10/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py", line 48, in coin
    my_dict[choice['Орёл', 'Решка']] = datetime.datetime.now().time()
            ~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2024-04-01 15:54:01,037 basehttp 9096 10444 "GET /myapp3/coin/10/ HTTP/1.1" 500 65446
INFO 2024-04-01 15:54:47,252 autoreload 9096 7024 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-01 15:54:47,698 autoreload 3228 10160 Watching for file changes with StatReloader
ERROR 2024-04-01 15:54:49,338 log 3228 2004 Internal Server Error: /myapp3/coin/10/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py", line 48, in coin
    my_dict[choice('Орёл', 'Решка')] = datetime.datetime.now().time()
            ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Random.choice() takes 2 positional arguments but 3 were given
ERROR 2024-04-01 15:54:49,339 basehttp 3228 2004 "GET /myapp3/coin/10/ HTTP/1.1" 500 65643
INFO 2024-04-01 15:55:53,128 autoreload 3228 10160 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-01 15:55:53,605 autoreload 8148 13576 Watching for file changes with StatReloader
INFO 2024-04-01 15:56:03,673 basehttp 8148 16740 "GET /myapp3/coin/10/ HTTP/1.1" 200 850
INFO 2024-04-01 15:56:11,403 basehttp 8148 16740 "GET /myapp3/coin/100/ HTTP/1.1" 200 850
INFO 2024-04-01 16:06:09,246 autoreload 8148 13576 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-01 16:06:09,693 autoreload 15368 17044 Watching for file changes with StatReloader
INFO 2024-04-01 16:06:11,971 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4720
INFO 2024-04-01 16:06:55,776 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4728
INFO 2024-04-01 16:07:01,800 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4708
INFO 2024-04-01 16:07:02,818 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4710
INFO 2024-04-01 16:07:03,484 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4692
INFO 2024-04-01 16:07:04,084 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4704
INFO 2024-04-01 16:07:04,670 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4706
INFO 2024-04-01 16:07:05,202 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4704
INFO 2024-04-01 16:07:05,629 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4722
INFO 2024-04-01 16:07:07,024 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4732
INFO 2024-04-01 16:07:25,991 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 4718
INFO 2024-04-01 16:07:26,721 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5614
INFO 2024-04-01 16:07:27,402 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5614
INFO 2024-04-01 16:07:27,904 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5612
INFO 2024-04-01 16:07:28,219 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5626
INFO 2024-04-01 16:07:28,408 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5618
INFO 2024-04-01 16:07:28,565 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5622
INFO 2024-04-01 16:07:29,037 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5610
INFO 2024-04-01 16:07:29,428 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5622
INFO 2024-04-01 16:07:29,794 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5618
INFO 2024-04-01 16:07:30,124 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5620
INFO 2024-04-01 16:07:30,311 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5612
INFO 2024-04-01 16:07:30,477 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5606
INFO 2024-04-01 16:07:30,634 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5600
INFO 2024-04-01 16:07:30,792 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5620
INFO 2024-04-01 16:07:30,941 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5616
INFO 2024-04-01 16:07:31,100 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5614
INFO 2024-04-01 16:07:31,258 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5602
INFO 2024-04-01 16:07:31,415 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5636
INFO 2024-04-01 16:07:31,565 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5620
INFO 2024-04-01 16:07:31,715 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5608
INFO 2024-04-01 16:07:45,957 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5610
INFO 2024-04-01 16:07:46,618 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5606
INFO 2024-04-01 16:08:01,527 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 5614
INFO 2024-04-01 16:08:02,120 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 7138
INFO 2024-04-01 16:08:02,532 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 7126
INFO 2024-04-01 16:08:02,704 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 7122
INFO 2024-04-01 16:08:02,855 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 7104
INFO 2024-04-01 16:08:03,012 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 7116
INFO 2024-04-01 16:08:03,177 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 7120
INFO 2024-04-01 16:08:03,382 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 7118
INFO 2024-04-01 16:08:03,530 basehttp 15368 17864 "GET /myapp3/coin/100/ HTTP/1.1" 200 7136
INFO 2024-04-01 16:09:44,423 autoreload 15368 17044 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-01 16:09:44,864 autoreload 5820 2436 Watching for file changes with StatReloader
INFO 2024-04-01 16:09:51,285 basehttp 5820 8900 "GET /myapp3/cub/10/ HTTP/1.1" 200 1125
INFO 2024-04-01 16:10:06,629 basehttp 5820 8900 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1147
INFO 2024-04-01 16:11:15,936 basehttp 5820 8900 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1219
INFO 2024-04-01 16:11:16,633 basehttp 5820 8900 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1219
INFO 2024-04-01 16:11:17,570 basehttp 5820 8900 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1220
INFO 2024-04-01 16:11:31,052 autoreload 17900 4168 Watching for file changes with StatReloader
INFO 2024-04-01 16:11:33,433 basehttp 17900 17284 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1218
INFO 2024-04-01 16:11:34,139 basehttp 17900 17284 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1218
INFO 2024-04-01 16:12:00,357 autoreload 16852 8880 Watching for file changes with StatReloader
INFO 2024-04-01 16:12:03,472 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1261
INFO 2024-04-01 16:12:04,399 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1259
INFO 2024-04-01 16:12:05,599 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1261
INFO 2024-04-01 16:12:06,027 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1260
INFO 2024-04-01 16:12:06,192 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1261
INFO 2024-04-01 16:12:06,364 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1260
INFO 2024-04-01 16:12:06,537 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1260
INFO 2024-04-01 16:12:06,875 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1259
INFO 2024-04-01 16:12:07,204 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1261
INFO 2024-04-01 16:12:07,601 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1259
INFO 2024-04-01 16:12:07,978 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1260
INFO 2024-04-01 16:12:08,382 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1258
INFO 2024-04-01 16:12:09,072 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1261
INFO 2024-04-01 16:12:09,319 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1258
INFO 2024-04-01 16:12:09,491 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1260
INFO 2024-04-01 16:12:09,642 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1260
INFO 2024-04-01 16:12:09,791 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1258
INFO 2024-04-01 16:12:10,055 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1261
INFO 2024-04-01 16:12:10,264 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1260
INFO 2024-04-01 16:12:10,430 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1260
INFO 2024-04-01 16:12:10,564 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1260
INFO 2024-04-01 16:12:10,714 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1259
INFO 2024-04-01 16:12:10,864 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1259
INFO 2024-04-01 16:12:11,021 basehttp 16852 16108 "GET /myapp3/numbers/10/ HTTP/1.1" 200 1261
INFO 2024-04-05 14:06:02,422 autoreload 1932 8440 Watching for file changes with StatReloader
WARNING 2024-04-05 14:06:13,325 log 1932 1972 Not Found: /
WARNING 2024-04-05 14:06:13,326 basehttp 1932 1972 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-05 14:06:19,982 log 1932 1972 Not Found: /game_choice
WARNING 2024-04-05 14:06:19,982 basehttp 1932 1972 "GET /game_choice HTTP/1.1" 404 2435
INFO 2024-04-05 14:06:34,832 basehttp 1932 1972 "GET /myapp3/game_choice HTTP/1.1" 301 0
INFO 2024-04-05 14:06:34,844 basehttp 1932 19108 "GET /myapp3/game_choice/ HTTP/1.1" 200 1355
INFO 2024-04-05 14:06:45,156 views 1932 19108 Получили: name='coin', count=10
ERROR 2024-04-05 14:06:45,177 log 1932 19108 Internal Server Error: /myapp3/game_choice/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py", line 66, in game_choice
    coin(count)
TypeError: coin() missing 1 required positional argument: 'count'
ERROR 2024-04-05 14:06:45,178 basehttp 1932 19108 "POST /myapp3/game_choice/ HTTP/1.1" 500 66950
INFO 2024-04-05 14:08:16,055 autoreload 1932 8440 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-05 14:08:16,514 autoreload 9708 4120 Watching for file changes with StatReloader
INFO 2024-04-05 14:08:18,930 views 9708 4476 Получили: name='coin', count=10
INFO 2024-04-05 14:08:18,946 basehttp 9708 4476 "POST /myapp3/game_choice/ HTTP/1.1" 200 1375
INFO 2024-04-05 14:08:20,961 views 9708 4476 Получили: name='coin', count=10
INFO 2024-04-05 14:08:20,963 basehttp 9708 4476 "POST /myapp3/game_choice/ HTTP/1.1" 200 1375
INFO 2024-04-05 14:08:23,921 views 9708 4476 Получили: name='coin', count=10
INFO 2024-04-05 14:08:23,923 basehttp 9708 4476 "POST /myapp3/game_choice/ HTTP/1.1" 200 1375
INFO 2024-04-05 14:18:13,920 autoreload 9708 4120 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-05 14:18:14,475 autoreload 7068 13616 Watching for file changes with StatReloader
INFO 2024-04-05 14:18:17,445 views 7068 11660 Получили: name='coin', count=10
ERROR 2024-04-05 14:18:17,478 log 7068 11660 Internal Server Error: /myapp3/game_choice/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp3.views.game_choice didn't return an HttpResponse object. It returned None instead.
ERROR 2024-04-05 14:18:17,478 basehttp 7068 11660 "POST /myapp3/game_choice/ HTTP/1.1" 500 67346
INFO 2024-04-05 14:18:26,027 autoreload 7068 13616 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-05 14:18:26,608 autoreload 6308 5492 Watching for file changes with StatReloader
INFO 2024-04-05 14:18:28,126 views 6308 3204 Получили: name='coin', count=10
INFO 2024-04-05 14:18:28,138 basehttp 6308 3204 "POST /myapp3/game_choice/ HTTP/1.1" 200 1375
INFO 2024-04-05 14:18:29,104 views 6308 3204 Получили: name='coin', count=10
INFO 2024-04-05 14:18:29,106 basehttp 6308 3204 "POST /myapp3/game_choice/ HTTP/1.1" 200 1375
INFO 2024-04-05 14:18:29,638 views 6308 3204 Получили: name='coin', count=10
INFO 2024-04-05 14:18:29,639 basehttp 6308 3204 "POST /myapp3/game_choice/ HTTP/1.1" 200 1375
INFO 2024-04-05 14:18:30,213 views 6308 3204 Получили: name='coin', count=10
INFO 2024-04-05 14:18:30,215 basehttp 6308 3204 "POST /myapp3/game_choice/ HTTP/1.1" 200 1375
INFO 2024-04-05 14:18:31,068 views 6308 3204 Получили: name='coin', count=10
INFO 2024-04-05 14:18:31,070 basehttp 6308 3204 "POST /myapp3/game_choice/ HTTP/1.1" 200 1375
INFO 2024-04-05 14:18:31,654 views 6308 3204 Получили: name='coin', count=10
INFO 2024-04-05 14:18:31,656 basehttp 6308 3204 "POST /myapp3/game_choice/ HTTP/1.1" 200 1375
INFO 2024-04-05 14:18:32,482 views 6308 3204 Получили: name='coin', count=10
INFO 2024-04-05 14:18:32,484 basehttp 6308 3204 "POST /myapp3/game_choice/ HTTP/1.1" 200 1375
INFO 2024-04-05 14:19:51,275 autoreload 6308 5492 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-05 14:19:51,736 autoreload 15876 19324 Watching for file changes with StatReloader
INFO 2024-04-05 14:19:54,130 views 15876 18084 Получили: name='coin', count=10
INFO 2024-04-05 14:19:54,142 basehttp 15876 18084 "POST /myapp3/game_choice/ HTTP/1.1" 200 1359
INFO 2024-04-05 14:19:55,551 views 15876 18084 Получили: name='coin', count=10
INFO 2024-04-05 14:19:55,553 basehttp 15876 18084 "POST /myapp3/game_choice/ HTTP/1.1" 200 1359
INFO 2024-04-05 14:23:18,160 autoreload 15876 19324 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-05 14:23:18,619 autoreload 10388 16656 Watching for file changes with StatReloader
INFO 2024-04-05 14:23:19,348 views 10388 19832 Получили: name='coin', count=10
INFO 2024-04-05 14:23:19,353 basehttp 10388 19832 "POST /myapp3/game_choice/ HTTP/1.1" 200 1202
INFO 2024-04-05 14:23:38,762 views 10388 19832 Получили: name='cub', count=10
INFO 2024-04-05 14:23:38,765 basehttp 10388 19832 "POST /myapp3/game_choice/ HTTP/1.1" 200 1125
INFO 2024-04-05 14:23:45,234 views 10388 19832 Получили: name='numbers', count=10
INFO 2024-04-05 14:23:45,236 basehttp 10388 19832 "POST /myapp3/game_choice/ HTTP/1.1" 200 1149
INFO 2024-04-05 14:24:21,888 views 10388 19832 Получили: name='numbers', count=10
INFO 2024-04-05 14:24:21,890 basehttp 10388 19832 "POST /myapp3/game_choice/ HTTP/1.1" 200 1177
INFO 2024-04-05 14:24:31,857 views 10388 19832 Получили: name='numbers', count=10
INFO 2024-04-05 14:24:31,859 basehttp 10388 19832 "POST /myapp3/game_choice/ HTTP/1.1" 200 1176
INFO 2024-04-05 14:25:01,001 views 10388 19832 Получили: name='numbers', count=10
INFO 2024-04-05 14:25:01,003 basehttp 10388 19832 "POST /myapp3/game_choice/ HTTP/1.1" 200 1420
INFO 2024-04-05 14:26:10,138 views 10388 19832 Получили: name='numbers', count=10
INFO 2024-04-05 14:26:10,140 basehttp 10388 19832 "POST /myapp3/game_choice/ HTTP/1.1" 200 1176
INFO 2024-04-05 14:27:42,886 views 10388 19832 Получили: name='numbers', count=10
INFO 2024-04-05 14:27:42,887 basehttp 10388 19832 "POST /myapp3/game_choice/ HTTP/1.1" 200 1193
INFO 2024-04-05 14:28:34,290 views 10388 19832 Получили: name='numbers', count=10
INFO 2024-04-05 14:28:34,291 basehttp 10388 19832 "POST /myapp3/game_choice/ HTTP/1.1" 200 1264
INFO 2024-04-05 14:28:38,969 views 10388 19832 Получили: name='cub', count=10
INFO 2024-04-05 14:28:38,970 basehttp 10388 19832 "POST /myapp3/game_choice/ HTTP/1.1" 200 1241
INFO 2024-04-05 14:32:39,671 autoreload 10388 16656 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-05 14:32:40,128 autoreload 3384 16968 Watching for file changes with StatReloader
INFO 2024-04-05 15:03:50,918 autoreload 10364 19288 Watching for file changes with StatReloader
WARNING 2024-04-05 15:03:51,991 log 10364 16140 Not Found: /
WARNING 2024-04-05 15:03:51,992 basehttp 10364 16140 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-05 15:03:55,983 log 10364 16140 Not Found: /myapp3/
WARNING 2024-04-05 15:03:55,984 basehttp 10364 16140 "GET /myapp3/ HTTP/1.1" 404 3780
INFO 2024-04-05 15:04:03,682 basehttp 10364 16140 "GET /myapp3/add_author HTTP/1.1" 301 0
INFO 2024-04-05 15:04:03,696 basehttp 10364 296 "GET /myapp3/add_author/ HTTP/1.1" 200 1778
INFO 2024-04-05 15:09:10,320 autoreload 10364 19288 D:\GeekBrains\Django\Seminars\myproject\myapp3\forms.py changed, reloading.
INFO 2024-04-05 15:09:10,830 autoreload 11752 13076 Watching for file changes with StatReloader
ERROR 2024-04-05 15:09:12,289 log 11752 20092 Internal Server Error: /myapp3/add_author/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py", line 94, in add_author
    form = AuthorForm()
           ^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
ERROR 2024-04-05 15:09:12,290 basehttp 11752 20092 "GET /myapp3/add_author/ HTTP/1.1" 500 71022
INFO 2024-04-05 15:10:08,090 autoreload 11752 13076 D:\GeekBrains\Django\Seminars\myproject\myapp3\forms.py changed, reloading.
INFO 2024-04-05 15:10:08,533 autoreload 18640 10392 Watching for file changes with StatReloader
ERROR 2024-04-05 15:10:09,106 log 18640 20248 Internal Server Error: /myapp3/add_author/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py", line 94, in add_author
    form = AuthorForm()
           ^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
ERROR 2024-04-05 15:10:09,108 basehttp 18640 20248 "GET /myapp3/add_author/ HTTP/1.1" 500 71022
INFO 2024-04-05 15:10:26,041 autoreload 18640 10392 D:\GeekBrains\Django\Seminars\myproject\myapp3\forms.py changed, reloading.
INFO 2024-04-05 15:10:26,464 autoreload 14064 3016 Watching for file changes with StatReloader
INFO 2024-04-05 15:10:26,790 basehttp 14064 18508 "GET /myapp3/add_author/ HTTP/1.1" 200 1651
INFO 2024-04-05 15:10:36,872 autoreload 14064 3016 D:\GeekBrains\Django\Seminars\myproject\myapp3\forms.py changed, reloading.
INFO 2024-04-05 15:10:37,295 autoreload 17136 8536 Watching for file changes with StatReloader
INFO 2024-04-05 15:10:37,563 basehttp 17136 19072 "GET /myapp3/add_author/ HTTP/1.1" 200 1651
INFO 2024-04-05 15:10:39,045 basehttp 17136 19072 "GET /myapp3/add_author/ HTTP/1.1" 200 1651
INFO 2024-04-05 15:10:39,659 basehttp 17136 19072 "GET /myapp3/add_author/ HTTP/1.1" 200 1651
INFO 2024-04-05 15:10:39,817 basehttp 17136 19072 "GET /myapp3/add_author/ HTTP/1.1" 200 1651
INFO 2024-04-05 15:10:39,996 basehttp 17136 19072 "GET /myapp3/add_author/ HTTP/1.1" 200 1651
INFO 2024-04-05 15:12:27,260 autoreload 17136 8536 D:\GeekBrains\Django\Seminars\myproject\myapp3\forms.py changed, reloading.
INFO 2024-04-05 15:12:27,681 autoreload 1340 17736 Watching for file changes with StatReloader
INFO 2024-04-05 15:12:27,951 basehttp 1340 4252 "GET /myapp3/add_author/ HTTP/1.1" 200 1839
INFO 2024-04-05 15:13:18,220 views 1340 4252 Получили: name='Иван', second_name='Иванов', email='mail@mail.ru', biography='Родился. Стал автором. Умер.', birthday=datetime.date(2000, 4, 5)
ERROR 2024-04-05 15:13:18,315 log 1340 4252 Internal Server Error: /myapp3/add_author/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: table myapp3_author has no column named second_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py", line 91, in add_author
    author.save()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table myapp3_author has no column named second_name
ERROR 2024-04-05 15:13:18,320 basehttp 1340 4252 "POST /myapp3/add_author/ HTTP/1.1" 500 150778
INFO 2024-04-05 15:17:35,373 autoreload 13148 5004 Watching for file changes with StatReloader
INFO 2024-04-05 15:17:39,405 views 13148 12756 Получили: name='Иван', second_name='Иванов', email='mail@mail.ru', biography='Родился. Стал автором. Умер.', birthday=datetime.date(2000, 4, 5)
INFO 2024-04-05 15:17:39,419 basehttp 13148 12756 "POST /myapp3/add_author/ HTTP/1.1" 200 1945
INFO 2024-04-05 15:17:43,394 views 13148 12756 Получили: name='Иван', second_name='Иванов', email='mail@mail.ru', biography='Родился. Стал автором. Умер.', birthday=datetime.date(2000, 4, 5)
INFO 2024-04-05 15:17:43,400 basehttp 13148 12756 "POST /myapp3/add_author/ HTTP/1.1" 200 1945
INFO 2024-04-05 15:26:14,650 autoreload 13148 5004 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-05 15:26:15,081 autoreload 7160 7352 Watching for file changes with StatReloader
INFO 2024-04-07 15:49:40,892 autoreload 3268 13808 Watching for file changes with StatReloader
WARNING 2024-04-07 15:49:42,266 log 3268 18216 Not Found: /
WARNING 2024-04-07 15:49:42,267 basehttp 3268 18216 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-07 15:49:42,374 log 3268 18216 Not Found: /favicon.ico
WARNING 2024-04-07 15:49:42,375 basehttp 3268 18216 "GET /favicon.ico HTTP/1.1" 404 2435
ERROR 2024-04-07 15:49:56,015 log 3268 18216 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:49:56,017 basehttp 3268 18216 "GET /admin/ HTTP/1.1" 500 105096
WARNING 2024-04-07 15:50:50,234 log 3268 18216 Not Found: /
WARNING 2024-04-07 15:50:50,234 basehttp 3268 18216 "GET / HTTP/1.1" 404 2384
ERROR 2024-04-07 15:50:53,910 log 3268 18216 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:50:53,911 basehttp 3268 18216 "GET /admin/ HTTP/1.1" 500 105370
ERROR 2024-04-07 15:50:57,680 log 3268 18216 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:50:57,683 basehttp 3268 18216 "GET /admin/ HTTP/1.1" 500 105096
INFO 2024-04-07 15:51:36,351 autoreload 3268 13808 D:\GeekBrains\Django\Seminars\myproject\myproject\settings.py changed, reloading.
INFO 2024-04-07 15:51:36,802 autoreload 7240 4880 Watching for file changes with StatReloader
WARNING 2024-04-07 15:51:39,447 log 7240 6756 Not Found: /
WARNING 2024-04-07 15:51:39,447 basehttp 7240 6756 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-07 15:51:43,953 log 7240 6756 Not Found: /admn
WARNING 2024-04-07 15:51:43,954 basehttp 7240 6756 "GET /admn HTTP/1.1" 404 2414
ERROR 2024-04-07 15:51:49,330 log 7240 6756 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:51:49,332 basehttp 7240 6756 "GET /admin/ HTTP/1.1" 500 105370
ERROR 2024-04-07 15:51:49,949 log 7240 6756 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:51:49,952 basehttp 7240 6756 "GET /admin/ HTTP/1.1" 500 105096
ERROR 2024-04-07 15:51:52,687 log 7240 6756 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:51:52,688 basehttp 7240 6756 "GET /admin/ HTTP/1.1" 500 105370
ERROR 2024-04-07 15:51:59,830 log 7240 6756 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:51:59,833 basehttp 7240 6756 "GET /admin/ HTTP/1.1" 500 105370
ERROR 2024-04-07 15:52:02,230 log 7240 6756 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:52:02,232 basehttp 7240 6756 "GET /admin/ HTTP/1.1" 500 105096
INFO 2024-04-07 15:52:30,878 autoreload 16288 7680 Watching for file changes with StatReloader
WARNING 2024-04-07 15:52:33,240 log 16288 13512 Not Found: /
WARNING 2024-04-07 15:52:33,241 basehttp 16288 13512 "GET / HTTP/1.1" 404 2384
ERROR 2024-04-07 15:52:37,110 log 16288 13512 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:52:37,112 basehttp 16288 13512 "GET /admin/ HTTP/1.1" 500 105370
ERROR 2024-04-07 15:52:37,763 log 16288 13512 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:52:37,765 basehttp 16288 13512 "GET /admin/ HTTP/1.1" 500 105096
ERROR 2024-04-07 15:53:19,102 log 16288 13512 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:53:19,103 basehttp 16288 13512 "GET /admin/ HTTP/1.1" 500 105096
INFO 2024-04-07 15:54:35,168 autoreload 4636 8316 Watching for file changes with StatReloader
WARNING 2024-04-07 15:55:42,632 log 4636 9284 Not Found: /
WARNING 2024-04-07 15:55:42,632 basehttp 4636 9284 "GET / HTTP/1.1" 404 2384
WARNING 2024-04-07 15:55:52,975 log 4636 9284 Not Found: /myapp
WARNING 2024-04-07 15:55:52,975 basehttp 4636 9284 "GET /myapp HTTP/1.1" 404 2417
WARNING 2024-04-07 15:55:58,662 log 4636 9284 Not Found: /myapp3/
WARNING 2024-04-07 15:55:58,664 basehttp 4636 9284 "GET /myapp3/ HTTP/1.1" 404 3780
WARNING 2024-04-07 15:56:05,998 log 4636 9284 Not Found: /myapp3/admin
WARNING 2024-04-07 15:56:05,999 basehttp 4636 9284 "GET /myapp3/admin HTTP/1.1" 404 3795
INFO 2024-04-07 15:56:17,391 basehttp 4636 9284 "GET /myapp3/game_choice/ HTTP/1.1" 200 1339
INFO 2024-04-07 15:56:21,354 views 4636 9284 Получили: name='coin', count=10
INFO 2024-04-07 15:56:21,361 basehttp 4636 9284 "POST /myapp3/game_choice/ HTTP/1.1" 200 1322
INFO 2024-04-07 15:56:22,794 basehttp 4636 9284 "GET /myapp3/game_choice/ HTTP/1.1" 200 1339
WARNING 2024-04-07 15:56:24,448 log 4636 9284 Not Found: /
WARNING 2024-04-07 15:56:24,448 basehttp 4636 9284 "GET / HTTP/1.1" 404 2384
ERROR 2024-04-07 15:56:27,218 log 4636 9284 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:56:27,220 basehttp 4636 9284 "GET /admin/ HTTP/1.1" 500 105370
ERROR 2024-04-07 15:56:30,153 log 4636 9284 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:56:30,154 basehttp 4636 9284 "GET /admin/ HTTP/1.1" 500 105096
INFO 2024-04-07 15:58:03,958 autoreload 4636 8316 D:\GeekBrains\Django\Seminars\myproject\myproject\urls.py changed, reloading.
INFO 2024-04-07 15:58:04,367 autoreload 11572 11676 Watching for file changes with StatReloader
WARNING 2024-04-07 15:58:05,493 log 11572 3004 Not Found: /
WARNING 2024-04-07 15:58:05,494 basehttp 11572 3004 "GET / HTTP/1.1" 404 2384
ERROR 2024-04-07 15:58:08,199 log 11572 3004 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:58:08,201 basehttp 11572 3004 "GET /admin/ HTTP/1.1" 500 100282
ERROR 2024-04-07 15:58:09,049 log 11572 3004 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:58:09,051 basehttp 11572 3004 "GET /admin/ HTTP/1.1" 500 100008
INFO 2024-04-07 15:58:15,894 autoreload 11572 11676 D:\GeekBrains\Django\Seminars\myproject\myproject\urls.py changed, reloading.
INFO 2024-04-07 15:58:16,323 autoreload 6332 3688 Watching for file changes with StatReloader
INFO 2024-04-07 15:59:11,384 autoreload 6332 3688 D:\GeekBrains\Django\Seminars\myproject\myproject\urls.py changed, reloading.
INFO 2024-04-07 15:59:11,799 autoreload 18772 15220 Watching for file changes with StatReloader
WARNING 2024-04-07 15:59:14,444 log 18772 4116 Not Found: /
WARNING 2024-04-07 15:59:14,445 basehttp 18772 4116 "GET / HTTP/1.1" 404 2383
ERROR 2024-04-07 15:59:17,625 log 18772 4116 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:59:17,628 basehttp 18772 4116 "GET /admin/ HTTP/1.1" 500 105370
ERROR 2024-04-07 15:59:22,881 log 18772 4116 Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if request.path == reverse("admin:logout", current_app=self.name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 657, in app_dict
    self._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 594, in _populate
    url_pattern._populate()
  File "D:\GeekBrains\Django\venv\Lib\site-packages\django\urls\resolvers.py", line 568, in _populate
    for url_pattern in reversed(self.url_patterns):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'set' object is not reversible
ERROR 2024-04-07 15:59:22,883 basehttp 18772 4116 "GET /admin/ HTTP/1.1" 500 105096
INFO 2024-04-07 16:01:02,969 autoreload 18772 15220 D:\GeekBrains\Django\Seminars\myproject\myapp3\urls.py changed, reloading.
INFO 2024-04-07 16:01:03,394 autoreload 10936 15124 Watching for file changes with StatReloader
WARNING 2024-04-07 16:01:05,056 log 10936 10408 Not Found: /
WARNING 2024-04-07 16:01:05,058 basehttp 10936 10408 "GET / HTTP/1.1" 404 2383
INFO 2024-04-07 16:01:07,937 basehttp 10936 10408 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-04-07 16:01:07,958 basehttp 10936 10408 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
INFO 2024-04-07 16:01:09,327 basehttp 10936 10408 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-04-07 16:01:09,333 basehttp 10936 10408 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
INFO 2024-04-07 16:01:17,387 basehttp 10936 10408 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-04-07 16:01:17,409 basehttp 10936 10408 "GET /admin/ HTTP/1.1" 200 5944
INFO 2024-04-07 16:01:17,415 basehttp 10936 10408 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2024-04-07 16:01:17,426 basehttp 10936 10408 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:01:17,426 basehttp 10936 5916 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:07:26,995 autoreload 10936 15124 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:07:27,404 autoreload 5380 4316 Watching for file changes with StatReloader
INFO 2024-04-07 16:07:31,861 basehttp 5380 16288 "GET /admin/ HTTP/1.1" 200 8368
INFO 2024-04-07 16:07:34,868 basehttp 5380 16288 "GET /admin/myapp3/author/ HTTP/1.1" 200 11273
INFO 2024-04-07 16:07:34,879 basehttp 5380 16288 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2024-04-07 16:07:34,881 basehttp 5380 13568 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2024-04-07 16:07:34,883 basehttp 5380 10448 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2024-04-07 16:07:34,884 basehttp 5380 19384 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2024-04-07 16:07:34,885 basehttp 5380 16288 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2024-04-07 16:07:34,885 basehttp 5380 12384 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2024-04-07 16:07:34,885 basehttp 5380 13568 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2024-04-07 16:07:34,908 basehttp 5380 15152 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:07:34,918 basehttp 5380 10448 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2024-04-07 16:07:34,918 basehttp 5380 19384 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2024-04-07 16:07:34,978 basehttp 5380 19384 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2024-04-07 16:07:34,992 basehttp 5380 19384 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:10:09,335 autoreload 5380 4316 D:\GeekBrains\Django\Seminars\myproject\myapp\admin.py changed, reloading.
INFO 2024-04-07 16:10:09,784 autoreload 1184 12048 Watching for file changes with StatReloader
INFO 2024-04-07 16:10:13,419 basehttp 1184 14348 "GET /admin/myapp3/author/ HTTP/1.1" 200 11801
INFO 2024-04-07 16:10:13,429 basehttp 1184 14348 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:10:52,901 basehttp 1184 14348 "GET /admin/auth/group/add/ HTTP/1.1" 200 16120
INFO 2024-04-07 16:10:52,910 basehttp 1184 14348 "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2024-04-07 16:10:52,912 basehttp 1184 5996 "GET /static/admin/js/SelectBox.js HTTP/1.1" 304 0
INFO 2024-04-07 16:10:52,913 basehttp 1184 11364 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 304 0
INFO 2024-04-07 16:10:52,914 basehttp 1184 3220 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2024-04-07 16:10:52,914 basehttp 1184 19452 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:10:52,919 basehttp 1184 19452 "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2024-04-07 16:10:52,920 basehttp 1184 3220 "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2024-04-07 16:10:52,955 basehttp 1184 5996 "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:10:52,955 basehttp 1184 3220 "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:10:52,957 basehttp 1184 11364 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:10:52,957 basehttp 1184 19452 "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:11:40,135 basehttp 1184 19452 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2024-04-07 16:11:40,146 basehttp 1184 19452 "GET /admin/auth/group/ HTTP/1.1" 200 11794
INFO 2024-04-07 16:11:40,172 basehttp 1184 19452 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:11:40,192 basehttp 1184 19452 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:11:44,537 basehttp 1184 19452 "GET /admin/auth/group/add/ HTTP/1.1" 200 16120
INFO 2024-04-07 16:11:44,544 basehttp 1184 19452 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:12:31,383 basehttp 1184 19452 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2024-04-07 16:12:31,393 basehttp 1184 19452 "GET /admin/auth/group/ HTTP/1.1" 200 12142
INFO 2024-04-07 16:12:31,402 basehttp 1184 19452 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:12:44,776 basehttp 1184 19452 "GET /admin/auth/group/add/ HTTP/1.1" 200 16120
INFO 2024-04-07 16:12:44,787 basehttp 1184 19452 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:13:33,756 basehttp 1184 19452 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2024-04-07 16:13:33,767 basehttp 1184 19452 "GET /admin/auth/group/ HTTP/1.1" 200 12512
INFO 2024-04-07 16:13:33,792 basehttp 1184 19452 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:14:23,144 basehttp 1184 19452 "GET /admin/auth/user/add/ HTTP/1.1" 200 13496
INFO 2024-04-07 16:14:23,154 basehttp 1184 19452 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:19:48,877 basehttp 1184 12240 "POST /admin/auth/user/add/ HTTP/1.1" 200 13929
INFO 2024-04-07 16:19:48,887 basehttp 1184 12240 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:20:07,728 basehttp 1184 12240 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2024-04-07 16:20:07,775 basehttp 1184 12240 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 27139
INFO 2024-04-07 16:20:07,783 basehttp 1184 5556 "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2024-04-07 16:20:07,783 basehttp 1184 7472 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2024-04-07 16:20:07,786 basehttp 1184 12240 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:20:07,840 basehttp 1184 12240 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:20:07,840 basehttp 1184 7472 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:20:20,886 basehttp 1184 7472 "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2024-04-07 16:20:20,905 basehttp 1184 7472 "GET /admin/auth/user/ HTTP/1.1" 200 15364
INFO 2024-04-07 16:20:20,912 basehttp 1184 7472 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:20:20,936 basehttp 1184 7472 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:20:20,937 basehttp 1184 12240 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2024-04-07 16:20:23,667 basehttp 1184 12240 "GET /admin/auth/user/add/ HTTP/1.1" 200 13496
INFO 2024-04-07 16:20:23,674 basehttp 1184 12240 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:20:36,172 basehttp 1184 12240 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2024-04-07 16:20:36,193 basehttp 1184 12240 "GET /admin/auth/user/3/change/ HTTP/1.1" 200 27139
INFO 2024-04-07 16:20:36,202 basehttp 1184 12240 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:20:41,705 basehttp 1184 12240 "POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
INFO 2024-04-07 16:20:41,719 basehttp 1184 12240 "GET /admin/auth/user/add/ HTTP/1.1" 200 13788
INFO 2024-04-07 16:20:41,728 basehttp 1184 12240 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:20:56,071 basehttp 1184 12240 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2024-04-07 16:20:56,091 basehttp 1184 12240 "GET /admin/auth/user/4/change/ HTTP/1.1" 200 27139
INFO 2024-04-07 16:20:56,100 basehttp 1184 12240 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:20:59,531 basehttp 1184 12240 "POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
INFO 2024-04-07 16:20:59,545 basehttp 1184 12240 "GET /admin/auth/user/ HTTP/1.1" 200 16366
INFO 2024-04-07 16:20:59,555 basehttp 1184 12240 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:20:59,596 basehttp 1184 7472 "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
INFO 2024-04-07 16:21:02,977 basehttp 1184 7472 "GET /admin/auth/user/3/change/ HTTP/1.1" 200 26851
INFO 2024-04-07 16:21:02,985 basehttp 1184 7472 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:21:07,086 basehttp 1184 7472 "POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
INFO 2024-04-07 16:21:07,096 basehttp 1184 7472 "GET /admin/auth/user/ HTTP/1.1" 200 16366
INFO 2024-04-07 16:21:07,106 basehttp 1184 7472 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:21:09,943 basehttp 1184 7472 "GET /admin/auth/user/4/change/ HTTP/1.1" 200 26851
INFO 2024-04-07 16:21:09,954 basehttp 1184 7472 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:21:14,130 basehttp 1184 7472 "POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
INFO 2024-04-07 16:21:14,143 basehttp 1184 7472 "GET /admin/auth/user/ HTTP/1.1" 200 16366
INFO 2024-04-07 16:21:14,151 basehttp 1184 7472 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:22:49,911 basehttp 1184 7472 "GET /admin/myapp3/author/ HTTP/1.1" 200 11801
INFO 2024-04-07 16:22:49,921 basehttp 1184 7472 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:22:51,153 basehttp 1184 7472 "GET /admin/myapp3/author/2/change/ HTTP/1.1" 200 13772
INFO 2024-04-07 16:22:51,161 basehttp 1184 7472 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:23:48,319 autoreload 1184 12048 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:23:48,744 autoreload 2728 3428 Watching for file changes with StatReloader
INFO 2024-04-07 16:23:53,835 basehttp 2728 5084 "GET /admin/myapp3/author/ HTTP/1.1" 200 11801
INFO 2024-04-07 16:23:53,844 basehttp 2728 5084 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:23:55,859 basehttp 2728 5084 "GET /admin/myapp3/author/ HTTP/1.1" 200 11801
INFO 2024-04-07 16:23:55,867 basehttp 2728 5084 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:23:56,563 basehttp 2728 5084 "GET /admin/myapp3/author/ HTTP/1.1" 200 11801
INFO 2024-04-07 16:23:56,573 basehttp 2728 5084 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:23:58,160 basehttp 2728 5084 "GET /admin/myapp3/author/2/change/ HTTP/1.1" 200 13772
INFO 2024-04-07 16:23:58,171 basehttp 2728 5084 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:24:23,627 autoreload 2728 3428 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:24:24,073 autoreload 12396 18276 Watching for file changes with StatReloader
INFO 2024-04-07 16:24:25,097 basehttp 12396 3708 "GET /admin/myapp3/author/2/change/ HTTP/1.1" 200 13772
INFO 2024-04-07 16:24:25,108 basehttp 12396 3708 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:24:27,909 basehttp 12396 3708 "GET /admin/myapp3/author/ HTTP/1.1" 200 11801
INFO 2024-04-07 16:24:27,920 basehttp 12396 3708 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:24:30,284 basehttp 12396 3708 "GET /admin/myapp3/author/ HTTP/1.1" 200 11801
INFO 2024-04-07 16:24:30,292 basehttp 12396 3708 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:25:03,946 autoreload 12396 18276 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:25:04,377 autoreload 7572 13340 Watching for file changes with StatReloader
INFO 2024-04-07 16:25:53,371 autoreload 7572 13340 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:25:53,787 autoreload 11180 10392 Watching for file changes with StatReloader
INFO 2024-04-07 16:25:54,993 basehttp 11180 2036 "GET /admin/myapp3/author/ HTTP/1.1" 200 12117
INFO 2024-04-07 16:25:55,004 basehttp 11180 2036 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:26:01,387 basehttp 11180 2036 "GET /admin/myapp3/author/2/change/ HTTP/1.1" 200 13772
INFO 2024-04-07 16:26:01,395 basehttp 11180 2036 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:26:04,344 basehttp 11180 2036 "GET /admin/myapp3/author/ HTTP/1.1" 200 12117
INFO 2024-04-07 16:26:54,809 basehttp 11180 2036 "GET /admin/myapp3/author/2/change/ HTTP/1.1" 200 13772
INFO 2024-04-07 16:26:54,821 basehttp 11180 2036 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:29:31,604 autoreload 11180 10392 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:29:32,049 autoreload 15072 11584 Watching for file changes with StatReloader
INFO 2024-04-07 16:29:52,572 autoreload 15072 11584 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:29:52,989 autoreload 1520 3036 Watching for file changes with StatReloader
INFO 2024-04-07 16:29:54,324 basehttp 1520 18224 "GET /admin/myapp3/author/ HTTP/1.1" 200 13388
INFO 2024-04-07 16:29:54,335 basehttp 1520 18224 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:29:56,691 basehttp 1520 18224 "GET /admin/myapp3/author/ HTTP/1.1" 200 13388
INFO 2024-04-07 16:29:56,699 basehttp 1520 18224 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:30:00,347 basehttp 1520 18224 "GET /admin/myapp3/author/add/ HTTP/1.1" 200 13209
INFO 2024-04-07 16:30:00,355 basehttp 1520 18224 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:30:16,371 basehttp 1520 18224 "GET /static/admin/img/calendar-icons.svg HTTP/1.1" 200 1094
INFO 2024-04-07 16:30:47,490 basehttp 1520 18224 "POST /admin/myapp3/author/add/ HTTP/1.1" 302 0
INFO 2024-04-07 16:30:47,518 basehttp 1520 18224 "GET /admin/myapp3/author/ HTTP/1.1" 200 14162
INFO 2024-04-07 16:30:47,528 basehttp 1520 18224 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:30:53,537 basehttp 1520 18224 "GET /admin/myapp3/author/?birthday__gte=2024-01-01&birthday__lt=2025-01-01 HTTP/1.1" 200 11496
INFO 2024-04-07 16:30:53,545 basehttp 1520 18224 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:30:55,073 basehttp 1520 18224 "GET /admin/myapp3/author/?birthday__gte=2024-03-31&birthday__lt=2024-04-08 HTTP/1.1" 200 11496
INFO 2024-04-07 16:30:55,082 basehttp 1520 18224 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:30:56,244 basehttp 1520 18224 "GET /admin/myapp3/author/?birthday__gte=2024-04-07&birthday__lt=2024-04-08 HTTP/1.1" 200 11496
INFO 2024-04-07 16:30:56,253 basehttp 1520 18224 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:30:57,345 basehttp 1520 18224 "GET /admin/myapp3/author/? HTTP/1.1" 200 13878
INFO 2024-04-07 16:30:57,353 basehttp 1520 18224 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:37:14,187 basehttp 1520 11016 "GET /admin/myapp3/coin/ HTTP/1.1" 200 9644
INFO 2024-04-07 16:37:14,199 basehttp 1520 11016 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:37:17,100 basehttp 1520 11016 "GET /admin/myapp3/cub/ HTTP/1.1" 200 9637
INFO 2024-04-07 16:37:17,108 basehttp 1520 11016 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:37:18,259 basehttp 1520 11016 "GET /admin/myapp3/numbers/ HTTP/1.1" 200 9665
INFO 2024-04-07 16:37:18,268 basehttp 1520 11016 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:37:20,058 basehttp 1520 11016 "GET /admin/myapp3/coin/ HTTP/1.1" 200 9644
INFO 2024-04-07 16:37:20,069 basehttp 1520 11016 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:37:20,764 basehttp 1520 11016 "GET /admin/myapp3/cub/ HTTP/1.1" 200 9637
INFO 2024-04-07 16:37:20,771 basehttp 1520 11016 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:37:21,431 basehttp 1520 11016 "GET /admin/myapp3/numbers/ HTTP/1.1" 200 9665
INFO 2024-04-07 16:37:21,438 basehttp 1520 11016 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:41:07,400 autoreload 1520 3036 D:\GeekBrains\Django\Seminars\myproject\myapp3\views.py changed, reloading.
INFO 2024-04-07 16:41:07,815 autoreload 6296 14520 Watching for file changes with StatReloader
WARNING 2024-04-07 16:41:08,848 log 6296 18516 Not Found: /
WARNING 2024-04-07 16:41:08,849 basehttp 6296 18516 "GET / HTTP/1.1" 404 2383
WARNING 2024-04-07 16:41:14,384 log 6296 18516 Not Found: /myapp3/
WARNING 2024-04-07 16:41:14,385 basehttp 6296 18516 "GET /myapp3/ HTTP/1.1" 404 3779
INFO 2024-04-07 16:41:16,805 basehttp 6296 18516 "GET /myapp3/game_choice/ HTTP/1.1" 200 1339
INFO 2024-04-07 16:41:26,535 views 6296 18516 Получили: name='coin', count=30
INFO 2024-04-07 16:41:26,606 basehttp 6296 18516 "POST /myapp3/game_choice/ HTTP/1.1" 200 5086
INFO 2024-04-07 16:41:31,143 basehttp 6296 18516 "GET /myapp3/game_choice/ HTTP/1.1" 200 1339
INFO 2024-04-07 16:41:34,409 views 6296 18516 Получили: name='cub', count=30
INFO 2024-04-07 16:41:34,472 basehttp 6296 18516 "POST /myapp3/game_choice/ HTTP/1.1" 200 4821
INFO 2024-04-07 16:41:36,054 basehttp 6296 18516 "GET /myapp3/game_choice/ HTTP/1.1" 200 1339
INFO 2024-04-07 16:41:39,223 views 6296 18516 Получили: name='numbers', count=30
INFO 2024-04-07 16:41:39,285 basehttp 6296 18516 "POST /myapp3/game_choice/ HTTP/1.1" 200 4913
INFO 2024-04-07 16:41:44,385 basehttp 6296 18516 "GET /admin/myapp3/numbers/ HTTP/1.1" 200 26069
INFO 2024-04-07 16:41:44,395 basehttp 6296 18516 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:43:38,737 autoreload 6296 14520 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:43:39,230 autoreload 7856 9988 Watching for file changes with StatReloader
INFO 2024-04-07 16:43:43,543 basehttp 7856 18944 "GET /admin/myapp3/author/ HTTP/1.1" 200 13630
INFO 2024-04-07 16:43:43,553 basehttp 7856 18944 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:44:16,206 autoreload 7856 9988 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:44:16,710 autoreload 10196 19324 Watching for file changes with StatReloader
INFO 2024-04-07 16:44:22,518 basehttp 10196 6016 "GET /admin/myapp3/author/ HTTP/1.1" 200 13959
INFO 2024-04-07 16:44:22,529 basehttp 10196 6016 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:44:30,062 basehttp 10196 6016 "GET /admin/myapp3/author/?q=%D0%B8%D0%B2%D0%B0%D0%BD HTTP/1.1" 200 11633
INFO 2024-04-07 16:44:30,070 basehttp 10196 6016 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:44:34,361 basehttp 10196 6016 "GET /admin/myapp3/author/?q=%D0%98%D0%B2%D0%B0%D0%BD HTTP/1.1" 200 14044
INFO 2024-04-07 16:44:34,371 basehttp 10196 6016 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:49:55,547 autoreload 10196 19324 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:49:55,974 autoreload 13088 15856 Watching for file changes with StatReloader
INFO 2024-04-07 16:49:57,879 basehttp 13088 16996 "GET /admin/myapp3/author/?q=%D0%98%D0%B2%D0%B0%D0%BD HTTP/1.1" 200 14044
INFO 2024-04-07 16:49:57,887 basehttp 13088 16996 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:49:59,177 basehttp 13088 16996 "GET /admin/myapp3/author/2/change/?_changelist_filters=q%3D%25D0%2598%25D0%25B2%25D0%25B0%25D0%25BD HTTP/1.1" 200 13272
INFO 2024-04-07 16:49:59,188 basehttp 13088 16996 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:50:25,803 autoreload 13088 15856 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:50:26,253 autoreload 14504 19364 Watching for file changes with StatReloader
INFO 2024-04-07 16:50:27,567 basehttp 14504 9964 "GET /admin/myapp3/author/2/change/?_changelist_filters=q%3D%25D0%2598%25D0%25B2%25D0%25B0%25D0%25BD HTTP/1.1" 200 13977
INFO 2024-04-07 16:50:27,576 basehttp 14504 9964 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:51:02,151 autoreload 14504 19364 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:51:02,571 autoreload 12700 17152 Watching for file changes with StatReloader
INFO 2024-04-07 16:51:03,449 basehttp 12700 5792 "GET /admin/myapp3/author/2/change/?_changelist_filters=q%3D%25D0%2598%25D0%25B2%25D0%25B0%25D0%25BD HTTP/1.1" 200 13179
INFO 2024-04-07 16:51:03,460 basehttp 12700 5792 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:51:05,585 basehttp 12700 5792 "GET /admin/myapp3/author/2/change/?_changelist_filters=q%3D%25D0%2598%25D0%25B2%25D0%25B0%25D0%25BD HTTP/1.1" 200 13179
INFO 2024-04-07 16:51:05,595 basehttp 12700 5792 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:51:20,095 autoreload 12700 17152 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:51:20,536 autoreload 13324 18880 Watching for file changes with StatReloader
INFO 2024-04-07 16:51:21,290 basehttp 13324 8792 "GET /admin/myapp3/author/2/change/?_changelist_filters=q%3D%25D0%2598%25D0%25B2%25D0%25B0%25D0%25BD HTTP/1.1" 200 13737
INFO 2024-04-07 16:51:21,300 basehttp 13324 8792 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:54:45,126 autoreload 13324 18880 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:54:45,602 autoreload 9356 13040 Watching for file changes with StatReloader
INFO 2024-04-07 16:55:17,224 autoreload 9356 13040 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:55:17,639 autoreload 12920 11756 Watching for file changes with StatReloader
INFO 2024-04-07 16:55:55,332 autoreload 12920 11756 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:55:55,742 autoreload 15176 2644 Watching for file changes with StatReloader
INFO 2024-04-07 16:56:19,320 autoreload 5324 4316 Watching for file changes with StatReloader
INFO 2024-04-07 16:57:00,050 autoreload 5324 4316 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:57:00,450 autoreload 4580 5432 Watching for file changes with StatReloader
INFO 2024-04-07 16:57:12,843 autoreload 4580 5432 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 16:57:13,240 autoreload 13056 4488 Watching for file changes with StatReloader
INFO 2024-04-07 16:57:18,165 basehttp 13056 15028 "GET /admin/ HTTP/1.1" 200 12820
INFO 2024-04-07 16:57:20,013 basehttp 13056 15028 "GET /admin/myapp3/author/ HTTP/1.1" 200 13959
INFO 2024-04-07 16:57:20,024 basehttp 13056 15028 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:57:21,720 basehttp 13056 15028 "GET /admin/myapp3/author/2/change/ HTTP/1.1" 200 13798
INFO 2024-04-07 16:57:21,729 basehttp 13056 13368 "GET /static/admin/js/collapse.js HTTP/1.1" 304 0
INFO 2024-04-07 16:57:21,731 basehttp 13056 15028 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 16:59:52,323 basehttp 13056 15028 "GET /admin/myapp3/ HTTP/1.1" 200 7147
INFO 2024-04-07 17:00:04,179 basehttp 13056 15028 "GET /admin/myapp3/author/ HTTP/1.1" 200 13959
INFO 2024-04-07 17:00:04,190 basehttp 13056 15028 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 17:03:51,923 autoreload 13056 4488 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 17:03:52,405 autoreload 10876 14816 Watching for file changes with StatReloader
INFO 2024-04-07 17:03:54,052 basehttp 10876 11784 "GET /admin/myapp3/author/ HTTP/1.1" 200 13959
INFO 2024-04-07 17:03:54,061 basehttp 10876 11784 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 17:04:11,055 autoreload 10876 14816 D:\GeekBrains\Django\Seminars\myproject\myapp3\admin.py changed, reloading.
INFO 2024-04-07 17:04:11,476 autoreload 16376 11920 Watching for file changes with StatReloader
INFO 2024-04-07 17:04:11,970 basehttp 16376 19208 "GET /admin/myapp3/author/ HTTP/1.1" 200 14036
INFO 2024-04-07 17:04:11,979 basehttp 16376 19208 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-04-07 17:04:22,923 basehttp 16376 19208 "POST /admin/myapp3/author/ HTTP/1.1" 302 0
INFO 2024-04-07 17:04:22,935 basehttp 16376 19208 "GET /admin/myapp3/author/ HTTP/1.1" 200 14038
INFO 2024-04-07 17:04:22,944 basehttp 16376 19208 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
